# Generated by Django 5.2.11 on 2026-02-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('technical_issue', 'Technical Issue'), ('billing_issue', 'Billing Issue'), ('account_issue', 'Account Issue'), ('other', 'Other')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='appeal_images/')),
                ('status', models.CharField(choices=[('not_reviewed', 'Not reviewed'), ('considered', 'Considered'), ('rejected', 'Rejected')], default='not_reviewed', max_length=20)),
            ],
        ),
    ]
