# Generated by Django 5.2.11 on 2026-02-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='appeal_images/'),
        ),
    ]
