# Generated by Django 6.0.2 on 2026-03-07 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0004_appeal_author'),
        ('appeals', '0004_comment_author'),
    ]

    operations = [
    ]
